# Generated by Django 4.1.9 on 2024-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ghamsu", "0002_historicalsundaydivineserviceattendance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmember",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "L100"),
                    ("200", "L200"),
                    ("300", "L300"),
                    ("400", "L400"),
                    ("500", "L500"),
                    ("600", "L600"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="level_of_completion",
            field=models.CharField(
                choices=[("400", "L400"), ("600", "L600")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "L100"),
                    ("200", "L200"),
                    ("300", "L300"),
                    ("400", "L400"),
                    ("500", "L500"),
                    ("600", "L600"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="level_of_completion",
            field=models.CharField(
                choices=[("400", "L400"), ("600", "L600")], max_length=255
            ),
        ),
    ]
