# Generated by Django 4.1.9 on 2024-03-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ghamsu", "0003_alter_historicalmember_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmember",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "100"),
                    ("200", "200"),
                    ("300", "300"),
                    ("400", "400"),
                    ("500", "500"),
                    ("600", "600"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="level_of_completion",
            field=models.CharField(
                choices=[("400", "400"), ("600", "600")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "100"),
                    ("200", "200"),
                    ("300", "300"),
                    ("400", "400"),
                    ("500", "500"),
                    ("600", "600"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="level_of_completion",
            field=models.CharField(
                choices=[("400", "400"), ("600", "600")], max_length=255
            ),
        ),
    ]
