# Generated by Django 4.1.9 on 2024-03-26 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ghamsu", "0006_alter_associatesbirthdaysthismonth_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="associate",
            options={"verbose_name_plural": "ASSOCIATES"},
        ),
        migrations.AlterModelOptions(
            name="associatesbirthdaysthismonth",
            options={"verbose_name_plural": "Associates Birthdays This Month"},
        ),
        migrations.AlterModelOptions(
            name="associatesbirthdaystoday",
            options={"verbose_name_plural": "Associates Birthdays Today"},
        ),
        migrations.AlterModelOptions(
            name="birthdaysthismonth",
            options={"verbose_name_plural": "Members Birthdays This Month"},
        ),
        migrations.AlterModelOptions(
            name="birthdaystoday",
            options={"verbose_name_plural": "Members Birthdays Today"},
        ),
        migrations.AlterModelOptions(
            name="historicalassociate",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical associate",
                "verbose_name_plural": "historical ASSOCIATES",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalassociatesbirthdaysthismonth",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical associates birthdays this month",
                "verbose_name_plural": "historical Associates Birthdays This Month",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalassociatesbirthdaystoday",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical associates birthdays today",
                "verbose_name_plural": "historical Associates Birthdays Today",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbirthdaysthismonth",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical birthdays this month",
                "verbose_name_plural": "historical Members Birthdays This Month",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbirthdaystoday",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical birthdays today",
                "verbose_name_plural": "historical Members Birthdays Today",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmember",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical member",
                "verbose_name_plural": "historical MEMBERS",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmidweekserviceattendance",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical midweek service attendance",
                "verbose_name_plural": "historical Midweek Service Attendance",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmondayprayermeetingattendance",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical monday prayer meeting attendance",
                "verbose_name_plural": "historical Monday Prayer Meeting Attendance",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalotherattendance",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical other attendance",
                "verbose_name_plural": "historical Other Attendance",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrehearsalattendance",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical rehearsal attendance",
                "verbose_name_plural": "historical Rehearsal Attendance",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsundaydivineserviceattendance",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical sunday divine service attendance",
                "verbose_name_plural": "historical Sunday DivineService Attendance",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsundayprayermeetingattendance",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical sunday prayer meeting attendance",
                "verbose_name_plural": "historical Sunday Prayer Meeting Attendance",
            },
        ),
        migrations.AlterModelOptions(
            name="member",
            options={
                "permissions": [
                    ("can_view_alto_members", "Can view member whose part is Alto")
                ],
                "verbose_name_plural": "MEMBERS",
            },
        ),
        migrations.AlterModelOptions(
            name="midweekserviceattendance",
            options={"verbose_name_plural": "Midweek Service Attendance"},
        ),
        migrations.AlterModelOptions(
            name="mondayprayermeetingattendance",
            options={"verbose_name_plural": "Monday Prayer Meeting Attendance"},
        ),
        migrations.AlterModelOptions(
            name="otherattendance",
            options={"verbose_name_plural": "Other Attendance"},
        ),
        migrations.AlterModelOptions(
            name="rehearsalattendance",
            options={"verbose_name_plural": "Rehearsal Attendance"},
        ),
        migrations.AlterModelOptions(
            name="sundaydivineserviceattendance",
            options={"verbose_name_plural": "Sunday DivineService Attendance"},
        ),
        migrations.AlterModelOptions(
            name="sundayprayermeetingattendance",
            options={"verbose_name_plural": "Sunday Prayer Meeting Attendance"},
        ),
    ]
