# Generated by Django 4.1.9 on 2024-03-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ghamsu", "0007_alter_associate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmember",
            name="part",
            field=models.CharField(
                choices=[
                    ("Tenor", "Tenor"),
                    ("Soprano", "Soprano"),
                    ("Alto", "Alto"),
                    ("Bass", "Bass"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="part",
            field=models.CharField(
                choices=[
                    ("Tenor", "Tenor"),
                    ("Soprano", "Soprano"),
                    ("Alto", "Alto"),
                    ("Bass", "Bass"),
                ],
                max_length=255,
            ),
        ),
    ]
