# Generated by Django 4.1.9 on 2024-03-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ghamsu", "0008_alter_historicalmember_part_alter_member_part"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name_plural": "MEMBERS"},
        ),
    ]
